name: openfast_env
channels:
  - nodefaults
  - conda-forge
dependencies:
  - jupyterlab==3.5.*
  - pandas==1.5.*
  - matplotlib==3.6.*
  - doit==0.33.*
  - pip==22.*
  - cmake==3.*
  - pip:
      - http://github.com/ricklupton/openfast-python-toolbox/archive/228a982d92fa9e148224aa85ec1da094ee3efb1c.zip#egg=pyFAST
