name: openfast_env
channels:
  - nodefaults
  - conda-forge
dependencies:
  - jupyterlab==3.5.*
  - pandas==1.5.*
  - matplotlib==3.6.*
  - doit==0.33.*
  - pip==22.*
  - cmake==3.*
  - pip:
      - git+http://github.com/OpenFAST/python-toolbox@787092df79a558b849c45aa9c53adfb737beb386#egg=pyFAST
