name: openfast_env
channels:
  - conda-forge
dependencies:
  - openfast
  - jupyterlab
  - pandas
  - matplotlib
  - doit
  - pip:
      - git+http://github.com/OpenFAST/python-toolbox@e6427b11345b68921fd66024431b8fce25fe3dd0#egg=pyFAST
